test_01_log_in (testcases.test_schedule.TestScheduleTasks) ... VlifeTest    Sat, 27 May 2017 14:59:58 DEBUG    Start testing
VlifeTest    Sat, 27 May 2017 15:00:47 DEBUG    Filter file:E:\AutoTestDemo\TestScheduleTasks\temp\860BCMK22LD8_201705271500log_filter.log
FAIL
test_02_network_connection_update (testcases.test_schedule.TestScheduleTasks) ... VlifeTest    Sat, 27 May 2017 15:01:18 DEBUG    Start testing
VlifeTest    Sat, 27 May 2017 15:03:15 DEBUG    Get user id from userinfo.xml:
ok
test_03_clearcache_uid_update (testcases.test_schedule.TestScheduleTasks) ... VlifeTest    Sat, 27 May 2017 15:04:42 DEBUG    Start testing
VlifeTest    Sat, 27 May 2017 15:04:47 DEBUG    Get user id from userinfo.xml:
VlifeTest    Sat, 27 May 2017 15:05:26 DEBUG    Get user id from userinfo.xml:
FAIL

======================================================================
FAIL: test_01_log_in (testcases.test_schedule.TestScheduleTasks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:/AutoTestDemo/TestScheduleTasks\testcases\test_schedule.py", line 152, in test_01_log_in
    self.assertEqual(True,result)
AssertionError: True != False

======================================================================
FAIL: test_03_clearcache_uid_update (testcases.test_schedule.TestScheduleTasks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "E:/AutoTestDemo/TestScheduleTasks\testcases\test_schedule.py", line 201, in test_03_clearcache_uid_update
    self.assertIsNot(cur_uid,'')
AssertionError: unexpectedly identical: ''

----------------------------------------------------------------------
Ran 3 tests in 347.834s

FAILED (failures=2)
